import { APIConfig } from '@/config/api';

const CHAMPIONSHIP_AUTH_CONTROLLER = APIConfig.baseURL + '/auth';
const CHAMPIONSHIP_TEAM_CONTROLLER = APIConfig.baseURL + '/team';
const CHAMPIONSHIP_LEAGUE_CONTROLLER = APIConfig.baseURL + '/league';
const CHAMPIONSHIP_FOOTBALLER_CONTROLLER = APIConfig.baseURL + '/footballer';

export const END_POINTS = {
  AUTH: {
    LOGIN: `${CHAMPIONSHIP_AUTH_CONTROLLER}/login`,
    REGISTER: `${CHAMPIONSHIP_AUTH_CONTROLLER}/register`,
  },
  TEAM: {
    CREATE: `${CHAMPIONSHIP_TEAM_CONTROLLER}/create`,
    GET_ALL: `${CHAMPIONSHIP_TEAM_CONTROLLER}/get`,
    GET_BY_ID: `${CHAMPIONSHIP_TEAM_CONTROLLER}`,
    SEARCH: `${CHAMPIONSHIP_TEAM_CONTROLLER}/search`,
  },
  LEAGUE: {
    CREATE: `${CHAMPIONSHIP_LEAGUE_CONTROLLER}/create`,
    GET: `${CHAMPIONSHIP_LEAGUE_CONTROLLER}/get`,
  },
  FOOTBALLER: {
    CREATE: `${CHAMPIONSHIP_FOOTBALLER_CONTROLLER}/create`,
    GET: `${CHAMPIONSHIP_FOOTBALLER_CONTROLLER}/get`,
    GET_BY_ID: `${CHAMPIONSHIP_FOOTBALLER_CONTROLLER}`,
    UPDATE: `${CHAMPIONSHIP_FOOTBALLER_CONTROLLER}/update`,
  },
};
